[package]
name = "bongrrative"
authors = ["l1npengtul <l1npengtul@protonmail.com>", "BongBong Corporation <FACE_THE_BONGBONG@BONGBONG_THE_FUTURE>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.4"
tera = "1.17"

