[package]
name = "bongtalk"
authors = ["l1npengtul <l1npengtul@protonmail.com>", "BongBong Development Corporation <FACE_THE_BONGBONG@BONGBONG_THE_FUTURE>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.17"
once_cell = "1.16"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"

[dependencies.rhai]
version = "1.10"
features = ["internals", "sync", "metadata"]

[dependencies.ahash]
version = "0.8"
